---
title: "HW5"
author: "Justin Hsiang"
date: "5/6/2020"
output:
  word_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


```{r}
library(MASS)
library(tseries)
library(astsa)
library(forecast)
library(qpcR)
unemployment = read.csv("/Users/justinhsiang/Desktop/college.csv" )
unemployment = unemployment[2]
unrate = ts(unemployment, start = c(2000, 1), frequency  = 12)
t = 1:length(unrate)
length(unrate)
fit = lm(unrate~t)
hist(unrate, main = "Histogram of Unemployment Rate")
shapiro.test(unrate)
bcTransform = boxcox(unrate~t, plotit = TRUE)
```

```{r}
lambda = bcTransform$x[which(bcTransform$y == max(bcTransform$y))]
unrate.bc = (1/lambda)*(unrate^lambda-1)
unrate.log = log(unrate)
unrate.log
hist(unrate.log, main = "Log Transformed Unemployment Rate of College Graduates")
shapiro.test(unrate.log)
ts.plot(unrate, main = "Graduate Unemployment Rate Percentage Each Month", ylab = "Unemployment Rate")
ts.plot(unrate.bc, main = "Box-Cox Transformed")
ts.plot(unrate.log, main = "Log Transformed Unemployment Rate of College Graduates", ylab = "log(unemployment rate)")
```


```{r}
acf(unrate.log, lag.max = 60)
dunrate = diff(unrate,12)
ddunrate = diff(dunrate, 1)
plot(dunrate, main = "Unemployment Rate Percentage Seasonaly Adjusted", ylab = "seasonally differenced log(unemployment rate)")
plot(ddunrate, main = "Unemployment Rate adjusted for underlying trends", ylab = "seasonally and linearly adjusted log(unrate)")
acf(ddunrate, lag.max = 60)
pacf(ddunrate, lag.max = 100)
```


```{r}
arima(unrate.log , c(1,1,0), seasonal = list(order = c(2,1,1), period = 12, method = "ML"))
arima(unrate.log , c(1,1,1), seasonal = list(order = c(2,1,1), period = 12, method = "ML"))
aiccs = matrix(NA, nr = 12, nc = 12)
dimnames(aiccs) = list(p =0:11,q=0:11)
for( p in 0:11)
{
  for(q in 0:11)
  {
    aiccs[p+1,q+1] = AICc(arima(unrate.log , c(p,1,q), seasonal = list(order = c(2,1,1), period = 12, method = "ML")))
  }
}

```
$$X_t - .3297X_{t-1} - .0133X_{t-12} - .0392X_{t-24} = Z_t - .8199Z_{t-1}-.9459Z_{t-12}$$


```{r}
fit.i = arima(unrate.log , c(0,1,3), seasonal = list(order = c(2,1,1), period = 12, method = "ML"))
res.i = fit.i$residuals
layout(matrix(c(1,1,2,3),2,2,byrow = T))
ts.plot(res.i, main = "Fitted Residuals")
abline(h= mean(res.i), col = "red")
acf(res.i, main = "Autocorrelation")
pacf(res.i, main = "Partial Autocorrelation")
```

Yule-Walker:
```{r}
ar(x = res.i, aic = TRUE, order.max = NULL, method = c("yule-walker"))
Box.test(res.i, lag = 10, type = c("Box-Pierce"), fitdf = 2)
Box.test(res.i, lag =10, type = c("Ljung-Box"), fitdf = 2)
Box.test(res.i^2, lag = 10, type = c("Ljung-Box"), fitdf = 0)
```


```{r}
qqnorm(fit.i$residuals)
qqline(fit.i$residuals, col = "red")
shapiro.test(fit.i$residuals)
hist(fit.i$residuals)
```



```{r}
fit.ii = arima(unrate.log , c(1,1,1), seasonal = list(order = c(2,1,1), period = 12, method = "ML"))
res.ii = fit.ii$residuals
layout(matrix(c(1,1,2,3),2,2,byrow = T))
ts.plot(res.ii, main = "Fitted Residuals")
abline(h= mean(res.ii), col = "red")
acf(res.ii, lag.max = 10,main = "Autocorrelation")
pacf(res.ii,lag.max = 10, main = "Partial Autocorrelation")
```


```{r}
ar(x = res.ii, aic = TRUE, order.max = NULL, method = c("yule-walker"))
Box.test(res.ii, lag = 10, type = c("Box-Pierce"), fitdf = 2)
Box.test(res.ii, lag =10, type = c("Ljung-Box"), fitdf = 2)
Box.test(res.ii^2, lag = 10, type = c("Ljung-Box"), fitdf = 0)


```







```{r}
qqnorm(fit.ii$residuals)
qqline(fit.ii$residuals)
hist(fit.ii$residuals)
shapiro.test((fit.ii$residuals))
```


```{r}
train = unrate[1:216]
test = unrate[216:244]

pred = sarima.for(train, 28, 1,1,1,2,1,1, S=12, no.constant = FALSE, plot.all = F)
points(216:244, test, col = "blue")
title("Forecast Testing")
```

```{r}
forecast = sarima.for(unrate, 24, 1,1,1,2,1,1,S=12, no.constant = FALSE, plot.all =F)
title("Forecasting Unemployment for Next 2 Years")


```




